#!/bin/bash

. "$(dirname -- "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
ESLINT="$(git rev-parse --show-toplevel)/src/control-panel/node_modules/.bin/eslint"

if [ ! -x "$ESLINT" ]; then
  echo "\t\033[41mPlease install ESlint\033[0m (npm install)"
  exit 1
fi

if [ "$STAGED_FILES" = "" ]; then
  exit 0
fi

PASS=true

echo "\nRunning pre-commit validation:\n"

for FILE in $STAGED_FILES
do
  "$ESLINT" "$FILE"

  if [ "$?" -eq 0 ]; then
    echo "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    echo "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
