{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Weather Station", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cosapp\")\n    |> range(start: -120m)\n    |> filter(fn: (r) => r._measurement == \"weather station\" and r._field == \"temperature\")\n    |> yield()"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cosapp\")\n    |> range(start: -120m)\n    |> filter(fn: (r) => r._measurement == \"weather station\" and r._field == \"humidity\")\n    |> yield()"
    }
   ]
  },
  {
   "title": "Weather station",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"cosapp\")\n    |> range(start: -120m)\n    |> filter(fn: (r) => r._measurement == \"weather station\" and r._field == \"temperature\" or r._field == \"humidity\") \n    "
    }
   ]
  }
 ]
}